name: compilation
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          submodules: recursive

      - name: Get URCAP Changes
        id: urcap-change
        uses: tj-actions/changed-files@v17.2
        with:
          files: |
            it.unibz.smf.mjt_client_ur/*
            external/*

      - name: Script
        if: steps.urcap-change.outputs.any_changed == 'true'
        shell: bash
        run: |
          cd external/ur && bash build_image.sh
          source setup.sh
          cd ../../it.unibz.smf.mjt_client_ur && ur_mvn

      - name: Push URCAP to releases
        if: steps.urcap-change.outputs.any_changed == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: it.unibz.smf.mjt_client_ur/target/mjt_noether_client_ur-1.0-SNAPSHOT.urcap
          asset_name: mjt_noether_client_ur-1.0-SNAPSHOT.urcap
          tag: package
          overwrite: true
          body: "URCAP"

      - name: Get Server Changes
        id: server-change
        uses: tj-actions/changed-files@v17.2
        with:
          files: |
            docker/*
            modules/*
            services/*

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push server image
        #if: steps.server-change.outputs.any_changed == 'true'a
        uses: docker/build-push-action@v2
        with:
          tags: "rafa606/mjt-ur-server"
          file: "docker/image.dockerfile"
          push: true
